FROM supplantr/toolbox

RUN dnf install -y gcc
RUN dnf install -y perl
RUN dnf install -y go
RUN dnf install -y libxcb-devel
RUN dnf install -y libX11-devel

RUN dnf install -y xorg-x11-server-Xvfb
RUN dnf install -y firejail

RUN GO111MODULE=on go get golang.org/x/tools/gopls@latest
